#!/bin/bash
. ./environment

printf "Subscribe u1->ch1: "
curl $opts -XPUT $host/users/u1/channel/ch1 -d ''

printf "\nSubscribe u1->ch2: "
curl $opts -XPUT $host/users/u1/channel/ch2 -d ''

printf "\nSubscribe u2->ch2: "
curl $opts -XPUT $host/users/u2/channel/ch2 -d ''

printf "\nSubscribe u2->ch3: "
curl $opts -XPUT $host/users/u2/channel/ch3 -d ''

printf "\nTwo DM's u1->u2: "
curl $opts -H 'Content-Type: application/json' -XPOST $host/users/u1/messages/to/u2 -d '"Direct message u1 -> u2 #1"'
curl $opts -H 'Content-Type: application/json' -XPOST $host/users/u1/messages/to/u2 -d '"Direct message u1 -> u2 #2"'

printf "\nBroadcast u1 -> ch1: "
curl $opts -H 'Content-Type: application/json' -XPOST $host/users/u1/channel/ch1 -d '"Broadcast message u1 -> ch1"'

printf "\nBroadcast u1 -> ch2: "
curl $opts -H 'Content-Type: application/json' -XPOST $host/users/u1/channel/ch2 -d '"Broadcast message u1 -> ch2"'

printf "\nBroadcast u2 -> ch1: "
curl $opts -H 'Content-Type: application/json' -XPOST $host/users/u2/channel/ch2 -d '"Broadcast message u2 -> ch2"'

printf "\nBroadcast u2 -> ch3: "
curl $opts -H 'Content-Type: application/json' -XPOST $host/users/u2/channel/ch3 -d '"Broadcast message u2 -> ch3"'
